language: go
go:
  - 1.12.x
  - 1.13.x
go_import_path: zgo.at/utils
notifications:
  email: false
install:
script: |
  export GO111MODULE=on
  go test -race \
    -coverprofile=coverage.txt \
    -coverpkg=./... \
    ./...
  bash <(curl -s https://codecov.io/bash)
